# Pandas

Es una herramienta para el análisis y la manipulación de datos.

In [ ]:
import pandas as pd

## DataFrame

In [ ]:
empleados = pd.DataFrame({
    "nombre": ["Ana", "Luis", "Marta", "Carlos", "Lucía", "Pablo"],
    "departamento": ["IT", "RRHH", "IT", "Ventas", "Marketing", "Ventas"],
    "salario": [2800, 2300, 3200, 2500, 2600, 2400],
    "antiguedad": [3, 5, 7, 2, 4, 1],  # años
})

In [ ]:
print(empleados)

   nombre departamento  salario  antiguedad
0     Ana           IT     2800           3
1    Luis         RRHH     2300           5
2   Marta           IT     3200           7
3  Carlos       Ventas     2500           2
4   Lucía    Marketing     2600           4
5   Pablo       Ventas     2400           1

In [ ]:
empleados

   nombre departamento  salario  antiguedad
0     Ana           IT     2800           3
1    Luis         RRHH     2300           5
2   Marta           IT     3200           7
3  Carlos       Ventas     2500           2
4   Lucía    Marketing     2600           4
5   Pablo       Ventas     2400           1

## Extracción de columnas

In [ ]:
empleados['nombre']

0       Ana
1      Luis
2     Marta
3    Carlos
4     Lucía
5     Pablo
Name: nombre, dtype: object

In [ ]:
empleados[["nombre", "departamento"]]

   nombre departamento
0     Ana           IT
1    Luis         RRHH
2   Marta           IT
3  Carlos       Ventas
4   Lucía    Marketing
5   Pablo       Ventas

## Extracción de filas

In [ ]:
# Fila 1
empleados.iloc[1]

nombre          Luis
departamento    RRHH
salario         2300
antiguedad         5
Name: 1, dtype: object

In [ ]:
empleados.iloc[1:]

   nombre departamento  salario  antiguedad
1    Luis         RRHH     2300           5
2   Marta           IT     3200           7
3  Carlos       Ventas     2500           2
4   Lucía    Marketing     2600           4
5   Pablo       Ventas     2400           1

In [ ]:
empleados.iloc[2]["salario"]

np.int64(3200)

## Guardado del DataFrame en un fichero

In [ ]:
empleados.to_excel("empleados.xlsx")

## Carga de datos desde un fichero

In [ ]:
iadb_df = pd.read_csv("/content/drive/MyDrive/grupo_master_iabd.csv")

In [ ]:
iadb_df

,dni_numero,dni_letra,dni,apellidos,nombre,nombre_completo,email,genero,nota_primer_trimestre,nota_segundo_trimestre,nota_tercer_trimestre
0,51704177,L,51704177-L,Di Francesco,Béatrice,"Di Francesco, Béatrice",rdifrancesco0@parallels.com,Male,3.78,0.63,2.80
1,33290075,F,33290075-F,Grieve,Marylène,"Grieve, Marylène",rgrieve1@weebly.com,Male,0.28,5.40,8.58
2,27410474,P,27410474-P,Erickssen,Mylène,"Erickssen, Mylène",lerickssen2@parallels.com,Male,8.94,0.52,1.04
3,47919050,M,47919050-M,Shafto,Pò,"Shafto, Pò",mshafto3@g.co,Male,3.78,4.12,9.99
4,57897260,E,57897260-E,Uppett,Börje,"Uppett, Börje",duppett4@simplemachines.org,Male,2.85,0.53,0.48
5,70909782,R,70909782-R,Reisen,Méthode,"Reisen, Méthode",treisen5@goo.gl,Male,9.53,9.13,4.38
6,68577768,L,68577768-L,Boyet,Maëly,"Boyet, Maëly",rboyet6@archive.org,Male,4.09,9.69,2.72
7,62406373,C,62406373-C,Shingfield,Börje,"Shingfield, Börje",ashingfield7@psu.edu,Bigender,8.13,7.76,7.45
8,48486428,I,48486428-I,Gregorin,Mélina,"Gregorin, Mélina",kgregorin8@amazon.com,Female,6.75,5.21,2.88
9,71790642,S,71790642-S,Wardingley,Lén,"Wardingley, Lén",jwardingley9@live.com,Male,7.02,6.67,9.11
10,11098617,H,11098617-H,Shuter,Estée,"Shuter, Estée",cshutera@businessinsider.com,Male,5.79,3.27,6.50
11,85240136,W,85240136-W,Heatherington,Jú,"Heatherington, Jú",aheatheringtonb@quantcast.com,Female,2.44,1.50,1.86
12,42138660,L,42138660-L,Owlner,Simplifiés,"Owlner, Simplifiés",kowlnerc@dagondesign.com,Male,5.86,4.76,0.12
13,29630418,Y,29630418-Y,Markwelley,Cinéma,"Markwelley, Cinéma",amarkwelleyd@tamu.edu,Female,5.69,4.09,9.74
14,77004674,T,77004674-T,Hearns,Björn,"Hearns, Björn",bhearnse@nature.com,Male,0.94,8.95,3.69
15,70939733,J,70939733-J,Skace,André,"Skace, André",eskacef@nature.com,Male,1.43,3.06,5.22
16,99560123,I,99560123-I,Dimmack,Adélie,"Dimmack, Adélie",pdimmackg@latimes.com,Female,6.28,2.42,6.41
17,80130771,F,80130771-F,Gozzett,Irène,"Gozzett, Irène",agozzetth@linkedin.com,Male,8.19,9.83,8.44
18,69275924,A,69275924-A,Stanfield,Bérengère,"Stanfield, Bérengère",astanfieldi@mapquest.com,Female,8.48,8.28,9.07
19,83769935,P,83769935-P,Kemster,Miléna,"Kemster, Miléna",rkemsterj@jugem.jp,Female,1.71,3.61,3.53
20,99391958,I,99391958-I,Garforth,Adélaïde,"Garforth, Adélaïde",rgarforthk@whitehouse.gov,Female,7.31,7.31,9.70
21,39514470,M,39514470-M,O'Hagirtie,Mahélie,"O'Hagirtie, Mahélie",mohagirtiel@loc.gov,Female,8.85,8.49,1.77
22,71615365,D,71615365-D,Muress,Réservés,"Muress, Réservés",mmuressm@cbslocal.com,Female,6.61,1.60,1.69
23,15145796,S,15145796-S,Mullen,Renée,"Mullen, Renée",cmullenn@prweb.com,Female,8.44,3.37,5.62
24,85589535,S,85589535-S,McQuillan,Marlène,"McQuillan, Marlène",fmcquillano@blogs.com,Male,9.19,3.68,9.98
25,20223909,J,20223909-J,Yukhov,Liè,"Yukhov, Liè",cyukhovp@ebay.co.uk,Non-binary,4.79,7.38,9.17
26,32365245,Z,32365245-Z,Gregoire,Ruì,"Gregoire, Ruì",lgregoireq@de.vu,Female,3.75,9.58,0.72
27,18909159,Z,18909159-Z,Plevin,Maïlis,"Plevin, Maïlis",aplevinr@surveymonkey.com,Male,7.35,3.67,3.67
28,81688603,C,81688603-C,Feyer,Michèle,"Feyer, Michèle",jfeyers@netlog.com,Polygender,4.61,8.93,0.47
29,96448006,D,96448006-D,Harrowsmith,Ruò,"Harrowsmith, Ruò",eharrowsmitht@hibu.com,Male,4.01,5.25,8.35

## Borrado de columnas

In [ ]:
iadb_df.drop(columns=["dni_numero", "dni_letra"], inplace=True)

In [ ]:
iadb_df

,dni,apellidos,nombre,nombre_completo,email,genero,nota_primer_trimestre,nota_segundo_trimestre,nota_tercer_trimestre
0,51704177-L,Di Francesco,Béatrice,"Di Francesco, Béatrice",rdifrancesco0@parallels.com,Male,3.78,0.63,2.80
1,33290075-F,Grieve,Marylène,"Grieve, Marylène",rgrieve1@weebly.com,Male,0.28,5.40,8.58
2,27410474-P,Erickssen,Mylène,"Erickssen, Mylène",lerickssen2@parallels.com,Male,8.94,0.52,1.04
3,47919050-M,Shafto,Pò,"Shafto, Pò",mshafto3@g.co,Male,3.78,4.12,9.99
4,57897260-E,Uppett,Börje,"Uppett, Börje",duppett4@simplemachines.org,Male,2.85,0.53,0.48
5,70909782-R,Reisen,Méthode,"Reisen, Méthode",treisen5@goo.gl,Male,9.53,9.13,4.38
6,68577768-L,Boyet,Maëly,"Boyet, Maëly",rboyet6@archive.org,Male,4.09,9.69,2.72
7,62406373-C,Shingfield,Börje,"Shingfield, Börje",ashingfield7@psu.edu,Bigender,8.13,7.76,7.45
8,48486428-I,Gregorin,Mélina,"Gregorin, Mélina",kgregorin8@amazon.com,Female,6.75,5.21,2.88
9,71790642-S,Wardingley,Lén,"Wardingley, Lén",jwardingley9@live.com,Male,7.02,6.67,9.11
10,11098617-H,Shuter,Estée,"Shuter, Estée",cshutera@businessinsider.com,Male,5.79,3.27,6.50
11,85240136-W,Heatherington,Jú,"Heatherington, Jú",aheatheringtonb@quantcast.com,Female,2.44,1.50,1.86
12,42138660-L,Owlner,Simplifiés,"Owlner, Simplifiés",kowlnerc@dagondesign.com,Male,5.86,4.76,0.12
13,29630418-Y,Markwelley,Cinéma,"Markwelley, Cinéma",amarkwelleyd@tamu.edu,Female,5.69,4.09,9.74
14,77004674-T,Hearns,Björn,"Hearns, Björn",bhearnse@nature.com,Male,0.94,8.95,3.69
15,70939733-J,Skace,André,"Skace, André",eskacef@nature.com,Male,1.43,3.06,5.22
16,99560123-I,Dimmack,Adélie,"Dimmack, Adélie",pdimmackg@latimes.com,Female,6.28,2.42,6.41
17,80130771-F,Gozzett,Irène,"Gozzett, Irène",agozzetth@linkedin.com,Male,8.19,9.83,8.44
18,69275924-A,Stanfield,Bérengère,"Stanfield, Bérengère",astanfieldi@mapquest.com,Female,8.48,8.28,9.07
19,83769935-P,Kemster,Miléna,"Kemster, Miléna",rkemsterj@jugem.jp,Female,1.71,3.61,3.53
20,99391958-I,Garforth,Adélaïde,"Garforth, Adélaïde",rgarforthk@whitehouse.gov,Female,7.31,7.31,9.70
21,39514470-M,O'Hagirtie,Mahélie,"O'Hagirtie, Mahélie",mohagirtiel@loc.gov,Female,8.85,8.49,1.77
22,71615365-D,Muress,Réservés,"Muress, Réservés",mmuressm@cbslocal.com,Female,6.61,1.60,1.69
23,15145796-S,Mullen,Renée,"Mullen, Renée",cmullenn@prweb.com,Female,8.44,3.37,5.62
24,85589535-S,McQuillan,Marlène,"McQuillan, Marlène",fmcquillano@blogs.com,Male,9.19,3.68,9.98
25,20223909-J,Yukhov,Liè,"Yukhov, Liè",cyukhovp@ebay.co.uk,Non-binary,4.79,7.38,9.17
26,32365245-Z,Gregoire,Ruì,"Gregoire, Ruì",lgregoireq@de.vu,Female,3.75,9.58,0.72
27,18909159-Z,Plevin,Maïlis,"Plevin, Maïlis",aplevinr@surveymonkey.com,Male,7.35,3.67,3.67
28,81688603-C,Feyer,Michèle,"Feyer, Michèle",jfeyers@netlog.com,Polygender,4.61,8.93,0.47
29,96448006-D,Harrowsmith,Ruò,"Harrowsmith, Ruò",eharrowsmitht@hibu.com,Male,4.01,5.25,8.35

In [ ]:
iadb_df.drop(columns=["apellidos", "nombre"], inplace=True)

## Exploración del DataFrame

In [ ]:
iadb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   dni                     30 non-null     object
 1   nombre_completo         30 non-null     object
 2   email                   30 non-null     object
 3   genero                  30 non-null     object
 4   nota_primer_trimestre   30 non-null     float64
 5   nota_segundo_trimestre  30 non-null     float64
 6   nota_tercer_trimestre   30 non-null     float64
dtypes: float64(3), object(4)
memory usage: 1.8+ KB

In [ ]:
iadb_df.describe()

       nota_primer_trimestre  nota_segundo_trimestre  nota_tercer_trimestre
count              30.000000               30.000000              30.000000
mean                5.562333                5.289667               5.171667
std                 2.671537                3.009365               3.430810
min                 0.280000                0.520000               0.120000
25%                 3.780000                3.295000               2.075000
50%                 5.825000                4.985000               4.800000
75%                 7.935000                8.150000               8.545000
max                 9.530000                9.830000               9.990000

In [ ]:
# Listado con los nombres y las notas
iadb_df[["nombre_completo", "nota_primer_trimestre", "nota_segundo_trimestre", "nota_tercer_trimestre"]]

,nombre_completo,nota_primer_trimestre,nota_segundo_trimestre,nota_tercer_trimestre
0,"Di Francesco, Béatrice",3.78,0.63,2.80
1,"Grieve, Marylène",0.28,5.40,8.58
2,"Erickssen, Mylène",8.94,0.52,1.04
3,"Shafto, Pò",3.78,4.12,9.99
4,"Uppett, Börje",2.85,0.53,0.48
5,"Reisen, Méthode",9.53,9.13,4.38
6,"Boyet, Maëly",4.09,9.69,2.72
7,"Shingfield, Börje",8.13,7.76,7.45
8,"Gregorin, Mélina",6.75,5.21,2.88
9,"Wardingley, Lén",7.02,6.67,9.11
10,"Shuter, Estée",5.79,3.27,6.50
11,"Heatherington, Jú",2.44,1.50,1.86
12,"Owlner, Simplifiés",5.86,4.76,0.12
13,"Markwelley, Cinéma",5.69,4.09,9.74
14,"Hearns, Björn",0.94,8.95,3.69
15,"Skace, André",1.43,3.06,5.22
16,"Dimmack, Adélie",6.28,2.42,6.41
17,"Gozzett, Irène",8.19,9.83,8.44
18,"Stanfield, Bérengère",8.48,8.28,9.07
19,"Kemster, Miléna",1.71,3.61,3.53
20,"Garforth, Adélaïde",7.31,7.31,9.70
21,"O'Hagirtie, Mahélie",8.85,8.49,1.77
22,"Muress, Réservés",6.61,1.60,1.69
23,"Mullen, Renée",8.44,3.37,5.62
24,"McQuillan, Marlène",9.19,3.68,9.98
25,"Yukhov, Liè",4.79,7.38,9.17
26,"Gregoire, Ruì",3.75,9.58,0.72
27,"Plevin, Maïlis",7.35,3.67,3.67
28,"Feyer, Michèle",4.61,8.93,0.47
29,"Harrowsmith, Ruò",4.01,5.25,8.35

In [ ]:
campos_a_mostrar = ["nombre_completo", "nota_primer_trimestre", "nota_segundo_trimestre", "nota_tercer_trimestre"]
iadb_df[campos_a_mostrar]

,nombre_completo,nota_primer_trimestre,nota_segundo_trimestre,nota_tercer_trimestre
0,"Di Francesco, Béatrice",3.78,0.63,2.80
1,"Grieve, Marylène",0.28,5.40,8.58
2,"Erickssen, Mylène",8.94,0.52,1.04
3,"Shafto, Pò",3.78,4.12,9.99
4,"Uppett, Börje",2.85,0.53,0.48
5,"Reisen, Méthode",9.53,9.13,4.38
6,"Boyet, Maëly",4.09,9.69,2.72
7,"Shingfield, Börje",8.13,7.76,7.45
8,"Gregorin, Mélina",6.75,5.21,2.88
9,"Wardingley, Lén",7.02,6.67,9.11
10,"Shuter, Estée",5.79,3.27,6.50
11,"Heatherington, Jú",2.44,1.50,1.86
12,"Owlner, Simplifiés",5.86,4.76,0.12
13,"Markwelley, Cinéma",5.69,4.09,9.74
14,"Hearns, Björn",0.94,8.95,3.69
15,"Skace, André",1.43,3.06,5.22
16,"Dimmack, Adélie",6.28,2.42,6.41
17,"Gozzett, Irène",8.19,9.83,8.44
18,"Stanfield, Bérengère",8.48,8.28,9.07
19,"Kemster, Miléna",1.71,3.61,3.53
20,"Garforth, Adélaïde",7.31,7.31,9.70
21,"O'Hagirtie, Mahélie",8.85,8.49,1.77
22,"Muress, Réservés",6.61,1.60,1.69
23,"Mullen, Renée",8.44,3.37,5.62
24,"McQuillan, Marlène",9.19,3.68,9.98
25,"Yukhov, Liè",4.79,7.38,9.17
26,"Gregoire, Ruì",3.75,9.58,0.72
27,"Plevin, Maïlis",7.35,3.67,3.67
28,"Feyer, Michèle",4.61,8.93,0.47
29,"Harrowsmith, Ruò",4.01,5.25,8.35

In [ ]:
iadb_df.sort_values(by="nombre_completo")

,dni,nombre_completo,email,genero,nota_primer_trimestre,nota_segundo_trimestre,nota_tercer_trimestre
6,68577768-L,"Boyet, Maëly",rboyet6@archive.org,Male,4.09,9.69,2.72
0,51704177-L,"Di Francesco, Béatrice",rdifrancesco0@parallels.com,Male,3.78,0.63,2.80
16,99560123-I,"Dimmack, Adélie",pdimmackg@latimes.com,Female,6.28,2.42,6.41
2,27410474-P,"Erickssen, Mylène",lerickssen2@parallels.com,Male,8.94,0.52,1.04
28,81688603-C,"Feyer, Michèle",jfeyers@netlog.com,Polygender,4.61,8.93,0.47
20,99391958-I,"Garforth, Adélaïde",rgarforthk@whitehouse.gov,Female,7.31,7.31,9.70
17,80130771-F,"Gozzett, Irène",agozzetth@linkedin.com,Male,8.19,9.83,8.44
26,32365245-Z,"Gregoire, Ruì",lgregoireq@de.vu,Female,3.75,9.58,0.72
8,48486428-I,"Gregorin, Mélina",kgregorin8@amazon.com,Female,6.75,5.21,2.88
1,33290075-F,"Grieve, Marylène",rgrieve1@weebly.com,Male,0.28,5.40,8.58
29,96448006-D,"Harrowsmith, Ruò",eharrowsmitht@hibu.com,Male,4.01,5.25,8.35
14,77004674-T,"Hearns, Björn",bhearnse@nature.com,Male,0.94,8.95,3.69
11,85240136-W,"Heatherington, Jú",aheatheringtonb@quantcast.com,Female,2.44,1.50,1.86
19,83769935-P,"Kemster, Miléna",rkemsterj@jugem.jp,Female,1.71,3.61,3.53
13,29630418-Y,"Markwelley, Cinéma",amarkwelleyd@tamu.edu,Female,5.69,4.09,9.74
24,85589535-S,"McQuillan, Marlène",fmcquillano@blogs.com,Male,9.19,3.68,9.98
23,15145796-S,"Mullen, Renée",cmullenn@prweb.com,Female,8.44,3.37,5.62
22,71615365-D,"Muress, Réservés",mmuressm@cbslocal.com,Female,6.61,1.60,1.69
21,39514470-M,"O'Hagirtie, Mahélie",mohagirtiel@loc.gov,Female,8.85,8.49,1.77
12,42138660-L,"Owlner, Simplifiés",kowlnerc@dagondesign.com,Male,5.86,4.76,0.12
27,18909159-Z,"Plevin, Maïlis",aplevinr@surveymonkey.com,Male,7.35,3.67,3.67
5,70909782-R,"Reisen, Méthode",treisen5@goo.gl,Male,9.53,9.13,4.38
3,47919050-M,"Shafto, Pò",mshafto3@g.co,Male,3.78,4.12,9.99
7,62406373-C,"Shingfield, Börje",ashingfield7@psu.edu,Bigender,8.13,7.76,7.45
10,11098617-H,"Shuter, Estée",cshutera@businessinsider.com,Male,5.79,3.27,6.50
15,70939733-J,"Skace, André",eskacef@nature.com,Male,1.43,3.06,5.22
18,69275924-A,"Stanfield, Bérengère",astanfieldi@mapquest.com,Female,8.48,8.28,9.07
4,57897260-E,"Uppett, Börje",duppett4@simplemachines.org,Male,2.85,0.53,0.48
9,71790642-S,"Wardingley, Lén",jwardingley9@live.com,Male,7.02,6.67,9.11
25,20223909-J,"Yukhov, Liè",cyukhovp@ebay.co.uk,Non-binary,4.79,7.38,9.17

In [ ]:
iadb_df.sort_values(by="nombre_completo", inplace=True)

In [ ]:
# Creamos la columna nota_media con la media de las notas de los tres trimestres
iadb_df["nota_media"] = (iadb_df["nota_primer_trimestre"] + iadb_df["nota_segundo_trimestre"] + iadb_df["nota_tercer_trimestre"]) / 3

In [ ]:
iadb_df["nota_boletin"] = round(iadb_df["nota_media"])

In [ ]:
iadb_df

,dni,nombre_completo,email,genero,nota_primer_trimestre,nota_segundo_trimestre,nota_tercer_trimestre,nota_media,nota_boletin
6,68577768-L,"Boyet, Maëly",rboyet6@archive.org,Male,4.09,9.69,2.72,5.500000,6.0
0,51704177-L,"Di Francesco, Béatrice",rdifrancesco0@parallels.com,Male,3.78,0.63,2.80,2.403333,2.0
16,99560123-I,"Dimmack, Adélie",pdimmackg@latimes.com,Female,6.28,2.42,6.41,5.036667,5.0
2,27410474-P,"Erickssen, Mylène",lerickssen2@parallels.com,Male,8.94,0.52,1.04,3.500000,4.0
28,81688603-C,"Feyer, Michèle",jfeyers@netlog.com,Polygender,4.61,8.93,0.47,4.670000,5.0
20,99391958-I,"Garforth, Adélaïde",rgarforthk@whitehouse.gov,Female,7.31,7.31,9.70,8.106667,8.0
17,80130771-F,"Gozzett, Irène",agozzetth@linkedin.com,Male,8.19,9.83,8.44,8.820000,9.0
26,32365245-Z,"Gregoire, Ruì",lgregoireq@de.vu,Female,3.75,9.58,0.72,4.683333,5.0
8,48486428-I,"Gregorin, Mélina",kgregorin8@amazon.com,Female,6.75,5.21,2.88,4.946667,5.0
1,33290075-F,"Grieve, Marylène",rgrieve1@weebly.com,Male,0.28,5.40,8.58,4.753333,5.0
29,96448006-D,"Harrowsmith, Ruò",eharrowsmitht@hibu.com,Male,4.01,5.25,8.35,5.870000,6.0
14,77004674-T,"Hearns, Björn",bhearnse@nature.com,Male,0.94,8.95,3.69,4.526667,5.0
11,85240136-W,"Heatherington, Jú",aheatheringtonb@quantcast.com,Female,2.44,1.50,1.86,1.933333,2.0
19,83769935-P,"Kemster, Miléna",rkemsterj@jugem.jp,Female,1.71,3.61,3.53,2.950000,3.0
13,29630418-Y,"Markwelley, Cinéma",amarkwelleyd@tamu.edu,Female,5.69,4.09,9.74,6.506667,7.0
24,85589535-S,"McQuillan, Marlène",fmcquillano@blogs.com,Male,9.19,3.68,9.98,7.616667,8.0
23,15145796-S,"Mullen, Renée",cmullenn@prweb.com,Female,8.44,3.37,5.62,5.810000,6.0
22,71615365-D,"Muress, Réservés",mmuressm@cbslocal.com,Female,6.61,1.60,1.69,3.300000,3.0
21,39514470-M,"O'Hagirtie, Mahélie",mohagirtiel@loc.gov,Female,8.85,8.49,1.77,6.370000,6.0
12,42138660-L,"Owlner, Simplifiés",kowlnerc@dagondesign.com,Male,5.86,4.76,0.12,3.580000,4.0
27,18909159-Z,"Plevin, Maïlis",aplevinr@surveymonkey.com,Male,7.35,3.67,3.67,4.896667,5.0
5,70909782-R,"Reisen, Méthode",treisen5@goo.gl,Male,9.53,9.13,4.38,7.680000,8.0
3,47919050-M,"Shafto, Pò",mshafto3@g.co,Male,3.78,4.12,9.99,5.963333,6.0
7,62406373-C,"Shingfield, Börje",ashingfield7@psu.edu,Bigender,8.13,7.76,7.45,7.780000,8.0
10,11098617-H,"Shuter, Estée",cshutera@businessinsider.com,Male,5.79,3.27,6.50,5.186667,5.0
15,70939733-J,"Skace, André",eskacef@nature.com,Male,1.43,3.06,5.22,3.236667,3.0
18,69275924-A,"Stanfield, Bérengère",astanfieldi@mapquest.com,Female,8.48,8.28,9.07,8.610000,9.0
4,57897260-E,"Uppett, Börje",duppett4@simplemachines.org,Male,2.85,0.53,0.48,1.286667,1.0
9,71790642-S,"Wardingley, Lén",jwardingley9@live.com,Male,7.02,6.67,9.11,7.600000,8.0
25,20223909-J,"Yukhov, Liè",cyukhovp@ebay.co.uk,Non-binary,4.79,7.38,9.17,7.113333,7.0

In [ ]:
iadb_df["nota_boletin"] = iadb_df["nota_boletin"].astype(int)

In [ ]:
iadb_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 6 to 25
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   dni                     30 non-null     object
 1   nombre_completo         30 non-null     object
 2   email                   30 non-null     object
 3   genero                  30 non-null     object
 4   nota_primer_trimestre   30 non-null     float64
 5   nota_segundo_trimestre  30 non-null     float64
 6   nota_tercer_trimestre   30 non-null     float64
 7   nota_media              30 non-null     float64
 8   nota_boletin            30 non-null     int64
dtypes: float64(4), int64(1), object(4)
memory usage: 2.3+ KB

In [ ]:
# Mostrar todos los géneros que tenemos
iadb_df["genero"].unique()

array(['Male', 'Female', 'Polygender', 'Bigender', 'Non-binary'],
      dtype=object)

In [ ]:
# Cambio de géneros al español
iadb_df["genero"].replace({"Male": "Masculino", "Female": "Femenino", "Polygender": "Poligénero", "Bigender": "Bigénero", "Non-binary": "No binario"}, inplace=True)

/tmp/ipykernel_6535/1241672887.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iadb_df["genero"].replace({"Male": "Masculino", "Female": "Femenino", "Polygender": "Poligénero", "Bigender": "Bigénero", "Non-binary": "No binario"}, inplace=True)

In [ ]:
iadb_df

,dni,nombre_completo,email,genero,nota_primer_trimestre,nota_segundo_trimestre,nota_tercer_trimestre,nota_media,nota_boletin
6,68577768-L,"Boyet, Maëly",rboyet6@archive.org,Masculino,4.09,9.69,2.72,5.500000,6
0,51704177-L,"Di Francesco, Béatrice",rdifrancesco0@parallels.com,Masculino,3.78,0.63,2.80,2.403333,2
16,99560123-I,"Dimmack, Adélie",pdimmackg@latimes.com,Femenino,6.28,2.42,6.41,5.036667,5
2,27410474-P,"Erickssen, Mylène",lerickssen2@parallels.com,Masculino,8.94,0.52,1.04,3.500000,4
28,81688603-C,"Feyer, Michèle",jfeyers@netlog.com,Poligénero,4.61,8.93,0.47,4.670000,5
20,99391958-I,"Garforth, Adélaïde",rgarforthk@whitehouse.gov,Femenino,7.31,7.31,9.70,8.106667,8
17,80130771-F,"Gozzett, Irène",agozzetth@linkedin.com,Masculino,8.19,9.83,8.44,8.820000,9
26,32365245-Z,"Gregoire, Ruì",lgregoireq@de.vu,Femenino,3.75,9.58,0.72,4.683333,5
8,48486428-I,"Gregorin, Mélina",kgregorin8@amazon.com,Femenino,6.75,5.21,2.88,4.946667,5
1,33290075-F,"Grieve, Marylène",rgrieve1@weebly.com,Masculino,0.28,5.40,8.58,4.753333,5
29,96448006-D,"Harrowsmith, Ruò",eharrowsmitht@hibu.com,Masculino,4.01,5.25,8.35,5.870000,6
14,77004674-T,"Hearns, Björn",bhearnse@nature.com,Masculino,0.94,8.95,3.69,4.526667,5
11,85240136-W,"Heatherington, Jú",aheatheringtonb@quantcast.com,Femenino,2.44,1.50,1.86,1.933333,2
19,83769935-P,"Kemster, Miléna",rkemsterj@jugem.jp,Femenino,1.71,3.61,3.53,2.950000,3
13,29630418-Y,"Markwelley, Cinéma",amarkwelleyd@tamu.edu,Femenino,5.69,4.09,9.74,6.506667,7
24,85589535-S,"McQuillan, Marlène",fmcquillano@blogs.com,Masculino,9.19,3.68,9.98,7.616667,8
23,15145796-S,"Mullen, Renée",cmullenn@prweb.com,Femenino,8.44,3.37,5.62,5.810000,6
22,71615365-D,"Muress, Réservés",mmuressm@cbslocal.com,Femenino,6.61,1.60,1.69,3.300000,3
21,39514470-M,"O'Hagirtie, Mahélie",mohagirtiel@loc.gov,Femenino,8.85,8.49,1.77,6.370000,6
12,42138660-L,"Owlner, Simplifiés",kowlnerc@dagondesign.com,Masculino,5.86,4.76,0.12,3.580000,4
27,18909159-Z,"Plevin, Maïlis",aplevinr@surveymonkey.com,Masculino,7.35,3.67,3.67,4.896667,5
5,70909782-R,"Reisen, Méthode",treisen5@goo.gl,Masculino,9.53,9.13,4.38,7.680000,8
3,47919050-M,"Shafto, Pò",mshafto3@g.co,Masculino,3.78,4.12,9.99,5.963333,6
7,62406373-C,"Shingfield, Börje",ashingfield7@psu.edu,Bigénero,8.13,7.76,7.45,7.780000,8
10,11098617-H,"Shuter, Estée",cshutera@businessinsider.com,Masculino,5.79,3.27,6.50,5.186667,5
15,70939733-J,"Skace, André",eskacef@nature.com,Masculino,1.43,3.06,5.22,3.236667,3
18,69275924-A,"Stanfield, Bérengère",astanfieldi@mapquest.com,Femenino,8.48,8.28,9.07,8.610000,9
4,57897260-E,"Uppett, Börje",duppett4@simplemachines.org,Masculino,2.85,0.53,0.48,1.286667,1
9,71790642-S,"Wardingley, Lén",jwardingley9@live.com,Masculino,7.02,6.67,9.11,7.600000,8
25,20223909-J,"Yukhov, Liè",cyukhovp@ebay.co.uk,No binario,4.79,7.38,9.17,7.113333,7

In [ ]:
# Listado de aprobados (nombre y nota)
iadb_df[iadb_df["nota_boletin"] >= 5][["nombre_completo", "nota_boletin"]]

         nombre_completo  nota_boletin
6           Boyet, Maëly             6
16       Dimmack, Adélie             5
28        Feyer, Michèle             5
20    Garforth, Adélaïde             8
17        Gozzett, Irène             9
26         Gregoire, Ruì             5
8       Gregorin, Mélina             5
1       Grieve, Marylène             5
29      Harrowsmith, Ruò             6
14         Hearns, Björn             5
13    Markwelley, Cinéma             7
24    McQuillan, Marlène             8
23         Mullen, Renée             6
21   O'Hagirtie, Mahélie             6
27        Plevin, Maïlis             5
5        Reisen, Méthode             8
3             Shafto, Pò             6
7      Shingfield, Börje             8
10         Shuter, Estée             5
18  Stanfield, Bérengère             9
9        Wardingley, Lén             8
25           Yukhov, Liè             7

In [ ]:
# Nombre, nota media y nota del boletín de los que han sacado notable o sobresaliente
iadb_df[iadb_df["nota_boletin"] >= 7][["nombre_completo", "nota_media", "nota_boletin"]]

         nombre_completo  nota_media  nota_boletin
20    Garforth, Adélaïde    8.106667             8
17        Gozzett, Irène    8.820000             9
13    Markwelley, Cinéma    6.506667             7
24    McQuillan, Marlène    7.616667             8
5        Reisen, Méthode    7.680000             8
7      Shingfield, Börje    7.780000             8
18  Stanfield, Bérengère    8.610000             9
9        Wardingley, Lén    7.600000             8
25           Yukhov, Liè    7.113333             7

In [ ]:
# Igual pero ordenados por nota (de mayor a menor)
iadb_df[iadb_df["nota_boletin"] >= 7][["nombre_completo", "nota_media", "nota_boletin"]].sort_values(by="nota_boletin", ascending=False)

         nombre_completo  nota_media  nota_boletin
17        Gozzett, Irène    8.820000             9
18  Stanfield, Bérengère    8.610000             9
20    Garforth, Adélaïde    8.106667             8
5        Reisen, Méthode    7.680000             8
24    McQuillan, Marlène    7.616667             8
9        Wardingley, Lén    7.600000             8
7      Shingfield, Börje    7.780000             8
13    Markwelley, Cinéma    6.506667             7
25           Yukhov, Liè    7.113333             7

## Ejercicio

Crea un archivo con datos ficticios sobre vuelos, mascotas, coches o cualquier otra temática.
Carga el archivo con pandas y prueba el análisis y transformación de datos como hemos visto en clase.

In [ ]:
vuelosdb_df = pd.read_csv("/content/drive/MyDrive/vuelos.csv")
vuelosdb_df

,id_interno,codigo_internacional,vuelo,aerolinea,modelo_avion,origen,destino_previsto,estado_vuelo,pasajeros,tripulacion,altitud_crucero_pies
0,101,AAL11,AA11,American Airlines,Boeing 767-223ER,BOS,LAX,Hijacked,81,11,29000.0
1,102,UAL175,UA175,United Airlines,Boeing 767-222,BOS,LAX,Hijacked,56,9,31000.0
2,103,AAL77,AA77,American Airlines,Boeing 757-223,IAD,LAX,Hijacked,58,6,35000.0
3,104,UAL93,UA93,United Airlines,Boeing 757-222,EWR,SFO,Hijacked,37,7,35000.0
4,105,DAL15,DL15,Delta Air Lines,Boeing 777-232ER,FRA,ATL,Diverted,218,14,37000.0
5,106,COA55,CO55,Continental Airlines,Boeing 777-224ER,CDG,EWR,Diverted,245,15,36000.0
6,107,AAL1210,AA1210,American Airlines,Boeing 767-200,JFK,LAX,Diverted,142,10,33000.0
7,108,AAL201,AA201,American Airlines,Boeing 767-200,JFK,LAX,Diverted,138,10,33000.0
8,109,AAL311,AA311,American Airlines,Boeing 737-800,LGA,ORD,Diverted,115,6,28000.0
9,110,AAL1467,AA1467,American Airlines,Boeing 757-200,DEN,LAX,Diverted,160,8,35000.0
10,111,AAL578,AA578,American Airlines,MD-80,ABQ,ORD,Diverted,98,5,31000.0
11,112,AAL518,AA518,American Airlines,Boeing 757-200,MIA,JFK,Diverted,154,8,34000.0
12,113,AAL431,AA431,American Airlines,Boeing 767-300,MIA,SFO,Diverted,175,11,36000.0
13,114,AAL1495,AA1495,American Airlines,MD-80,PHL,DFW,Diverted,112,5,30000.0
14,115,SAM28000,AF1,US Air Force,Boeing VC-25A,SRQ,ADW,Diverted,45,26,40000.0

In [ ]:
vuelosdb_df[vuelosdb_df["estado_vuelo"] == "Hijacked"][["codigo_internacional", "aerolinea", "modelo_avion", "pasajeros"]]

  codigo_internacional          aerolinea      modelo_avion  pasajeros
0                AAL11  American Airlines  Boeing 767-223ER         81
1               UAL175    United Airlines    Boeing 767-222         56
2                AAL77  American Airlines    Boeing 757-223         58
3                UAL93    United Airlines    Boeing 757-222         37

In [ ]:
vuelosdb_df["total_ocupantes"] = vuelosdb_df["pasajeros"] + vuelosdb_df["tripulacion"]
vuelosdb_df

,id_interno,codigo_internacional,vuelo,aerolinea,modelo_avion,origen,destino_previsto,estado_vuelo,pasajeros,tripulacion,altitud_crucero_pies,total_ocupantes
0,101,AAL11,AA11,American Airlines,Boeing 767-223ER,BOS,LAX,Hijacked,81,11,29000.0,92
1,102,UAL175,UA175,United Airlines,Boeing 767-222,BOS,LAX,Hijacked,56,9,31000.0,65
2,103,AAL77,AA77,American Airlines,Boeing 757-223,IAD,LAX,Hijacked,58,6,35000.0,64
3,104,UAL93,UA93,United Airlines,Boeing 757-222,EWR,SFO,Hijacked,37,7,35000.0,44
4,105,DAL15,DL15,Delta Air Lines,Boeing 777-232ER,FRA,ATL,Diverted,218,14,37000.0,232
5,106,COA55,CO55,Continental Airlines,Boeing 777-224ER,CDG,EWR,Diverted,245,15,36000.0,260
6,107,AAL1210,AA1210,American Airlines,Boeing 767-200,JFK,LAX,Diverted,142,10,33000.0,152
7,108,AAL201,AA201,American Airlines,Boeing 767-200,JFK,LAX,Diverted,138,10,33000.0,148
8,109,AAL311,AA311,American Airlines,Boeing 737-800,LGA,ORD,Diverted,115,6,28000.0,121
9,110,AAL1467,AA1467,American Airlines,Boeing 757-200,DEN,LAX,Diverted,160,8,35000.0,168
10,111,AAL578,AA578,American Airlines,MD-80,ABQ,ORD,Diverted,98,5,31000.0,103
11,112,AAL518,AA518,American Airlines,Boeing 757-200,MIA,JFK,Diverted,154,8,34000.0,162
12,113,AAL431,AA431,American Airlines,Boeing 767-300,MIA,SFO,Diverted,175,11,36000.0,186
13,114,AAL1495,AA1495,American Airlines,MD-80,PHL,DFW,Diverted,112,5,30000.0,117
14,115,SAM28000,AF1,US Air Force,Boeing VC-25A,SRQ,ADW,Diverted,45,26,40000.0,71

In [ ]:
vuelosdb_df["altitud_m"] = round(vuelosdb_df["altitud_crucero_pies"] * 0.3048)
vuelosdb_df["altitud_m"] = vuelosdb_df["altitud_m"].astype(int)
vuelosdb_df

,id_interno,codigo_internacional,vuelo,aerolinea,modelo_avion,origen,destino_previsto,estado_vuelo,pasajeros,tripulacion,altitud_crucero_pies,total_ocupantes,altitud_m
0,101,AAL11,AA11,American Airlines,Boeing 767-223ER,BOS,LAX,Hijacked,81,11,29000.0,92,8839
1,102,UAL175,UA175,United Airlines,Boeing 767-222,BOS,LAX,Hijacked,56,9,31000.0,65,9449
2,103,AAL77,AA77,American Airlines,Boeing 757-223,IAD,LAX,Hijacked,58,6,35000.0,64,10668
3,104,UAL93,UA93,United Airlines,Boeing 757-222,EWR,SFO,Hijacked,37,7,35000.0,44,10668
4,105,DAL15,DL15,Delta Air Lines,Boeing 777-232ER,FRA,ATL,Diverted,218,14,37000.0,232,11278
5,106,COA55,CO55,Continental Airlines,Boeing 777-224ER,CDG,EWR,Diverted,245,15,36000.0,260,10973
6,107,AAL1210,AA1210,American Airlines,Boeing 767-200,JFK,LAX,Diverted,142,10,33000.0,152,10058
7,108,AAL201,AA201,American Airlines,Boeing 767-200,JFK,LAX,Diverted,138,10,33000.0,148,10058
8,109,AAL311,AA311,American Airlines,Boeing 737-800,LGA,ORD,Diverted,115,6,28000.0,121,8534
9,110,AAL1467,AA1467,American Airlines,Boeing 757-200,DEN,LAX,Diverted,160,8,35000.0,168,10668
10,111,AAL578,AA578,American Airlines,MD-80,ABQ,ORD,Diverted,98,5,31000.0,103,9449
11,112,AAL518,AA518,American Airlines,Boeing 757-200,MIA,JFK,Diverted,154,8,34000.0,162,10363
12,113,AAL431,AA431,American Airlines,Boeing 767-300,MIA,SFO,Diverted,175,11,36000.0,186,10973
13,114,AAL1495,AA1495,American Airlines,MD-80,PHL,DFW,Diverted,112,5,30000.0,117,9144
14,115,SAM28000,AF1,US Air Force,Boeing VC-25A,SRQ,ADW,Diverted,45,26,40000.0,71,12192

In [ ]:
iadb_df.to_csv("iadb_df_procesado.csv")